config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :admins
  root 'pages#home'

  get "gallery" => "pages#gallery", as: :gallery
  get "blog" => "pages#blog", as: :blog
  get "contact" => "pages#contact", as: :contact
  get "admin" => "pages#admin", as: :admin
  get "new" => "posts#new", as: :new

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
end

app/models/project.rb
class Project

  def Project.all
    client = Behance::Client.new(access_token: "EyNy4STT52F3iOYpOenUE6HzEiNFaVlk")
    client.user_projects("TimeTravelingTiger")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @active_page = "home"
    @projects = Project.all      
  end 

  def gallery
    @active_page = "gallery"
    @projects = Project.all
  end

  def blog
    @active_page = "blog"
    @posts = Post.all.order('created_at Desc')
  end

  def contact
    @active_page = "contact"
  end

  def admin
    @active_page = "admin"
    @posts = Post.all.order('created_at Desc')
  end
 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to admin_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :admin
  end

  def resource
    @resource ||= Admin.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:admin]
  end

  def tel_to(text)
    groups = text.to_s.scan(/(?:^\+)?\d+/)
    link_to text, "tel:#{groups.join '-'}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Time Traveling Tiger</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    
  </head>
  <body>
    <!-- Render devise partial -->
    <%= render "partials/login_modal" %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">

          <div class="top-pop slideDown">
            
          </div>
          <!-- Logo -->
          <div class="banner fadeIn">
            <%= image_tag("TTT-logo-v2_1.png", :size => "1100x125", :class => "img-responsive center-block") %>
          </div>
          
          <%= render 'partials/navbar' %>

          <!-- Render content page -->
          <div>
            <%= yield %>
          </div>
          
          <div class="divider-bottom slideUp">
            <!-- Admin Login Nav -->
            <div class="admin admin-buttons">
              <% if admin_signed_in? %>
                <ul class="list">      
                  <li><p><%= link_to 'Admin Page', admin_path %></p></li>
                  <li><p><%= link_to 'Log Out', destroy_admin_session_path, :method=>'delete' %></p></li>
                </ul>
              <% else %>
                <p><%= link_to "Login", "#login", "data-toggle" => "modal", :class =>'btn bt-small' %></p>
              <% end %>
            </div>
          </div>
          
          <!-- devise alerts -->
          <div class="post-style">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
          </div>

        </div>
      </div>
    </div>

  </body>
</html>

app/views/pages/admin.html.erb
<div class="container">
  

  <div class="col-xs-8 col-xs-offset-2">
    <ul class="admin-buttons list">      
      <li><p><%= link_to 'New', new_path %></p></li>
    </ul>
  </div>



  <div class="col-xs-8 col-xs-offset-2">
    <div class="post-style">
      <% @posts.each do |p| %>
        <h1 class="titles"><%= p.title %></h1></br>
        <p class="date"><%= p.created_at.strftime("%B %d, %Y") %></p>
        <ul class="row list admin-buttons">
          <li><%= link_to 'Edit', edit_post_path(p) %></li>
          <li><%= link_to 'Delete', post_path(p), method: :delete, data: {confirm: "Are you sure?"} %></li>
          
        </ul>
      <% end %>
    </div>
  </div>
  
</div> 

app/views/pages/blog.html.erb
<div class="divider">
  
</div>

<div class="container">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="post-style">
    <% @posts.each do |p| %>
      <h1 class="titles"><%= p.title %></h1></br>
      <p class="body"><%= p.body %></p></br>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container">
  <div class="col-xs-8 col-xs-offset-2 post-style">
    <p class="body">This is where the contact form will go</p>
  </div>
</div>

app/views/pages/gallery.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
      <div class="js-masonry transitions-enabled infinite-scroll clearfix" id="masonry-container"> 
        
        <% @projects.each do |project| %>
           
          <div class="box">
            <%= link_to (image_tag project["covers"]["404"]), project["url"], :class =>'pulse' %>
            <div class="panel-body">
              <h2 class="titles">
                <%= link_to project["name"], project["url"] %>
              <h2>
            </div>
            
          </div>
        <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-12 col-lg-12">
      
        <ul class="bxslider">
          <% @projects.each do |project| %>
            <li>
              <%= link_to (image_tag project["covers"]["404"]), project["url"], :class =>'img-responsive center block', :size => "1100x125"%>
            </li>
          <% end %>
          <div class="js-video [vimeo, widescreen]">
            <li>
              <iframe src="https://player.vimeo.com/video/120739736" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </li>
          </div>
        </ul>
      
      <h6 id="re-sponsive"><strong>Hey!</strong> If you are on a desktop or laptop try resizing your browser window.<br/>
        TTT brings responsive web design to life with elegant animations and thoughtful implementation of UI/UX principles!
      </h6>
      <div class="home-screen-panels fadeIn">
      
        <!-- Nav tabs -->
        <ul id="myTab" class="nav nav-tabs" role="tablist">
          
          <li role="presentation" class="active">
            <a href="#about" aria-controls="about" role="tab" data-toggle="tab">
              ABOUT
            </a>
          </li>

          <li role="presentation">
            <a href="#post-production" aria-controls="post-production" role="tab" data-toggle="tab">
              POST PRODUCTION
            </a>

          </li>

          <li role="presentation">
            <a href="#graphic-design" aria-controls="graphic-design" role="tab" data-toggle="tab">
              GRAPHIC DESIGN
            </a>
          </li>

          <li role="presentation">
            <a href="#web-development" aria-controls="web-development" role="tab" data-toggle="tab">
              WEB DEVELOPMENT
            </a>
          </li>

        </ul>

        <!-- Tab panes home-tab-content -->
        <div id="myTabContent" class="tab-content tab-panels">
          
          <div role="tabpanel" class="tab-pane fade in active" id="about">
            <%= render 'partials/about_panel' %>
          </div>

          <div role="tabpanel" class="tab-pane fade" id="post-production">
            <%= render 'partials/post_production_panel' %>
          </div>

          <div role="tabpanel" class="tab-pane fade" id="graphic-design">
            <%= render 'partials/graphic_design_panel' %>
          </div>

          <div role="tabpanel" class="tab-pane fade" id="web-development">
            <%= render 'partials/web_development_panel' %>
          </div>
        
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/partials/_about_panel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 post-production-panel-style">
      <p class="body panel-style">This is where I will welcome visitors to the page.</p>
    </div>
  </div>
</div>

app/views/partials/_design_development_panel.html.erb
<div class="container-fluid home-tab-content">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 post-style">
      <p class="body">This is where information about web design and development will go.</p>
    </div>
  </div>
</div>

app/views/partials/_graphic_design_panel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1 post-style">
      <p class="body panel-style">This is where information about graphic design will go.</p>
    </div>
  </div>
</div>

app/views/partials/_j_tron.html.erb
<div id="jumbotron-1" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#jumbotron-1" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#jumbotron-1" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/partials/_j_tron_two.html.erb
<div id="jumbotron-2" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <%= image_tag("stripes.jpg") %>
      <div class="carousel-caption">
        ...
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#jumbotron-2" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#jumbotron-2" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/partials/_login_modal.html.erb
<div class="modal fade" id="login">
  <div class="modal-dialog">
    <div class="modal-content modal-style">
      <div class="modal-header">
        <div class="modal-style">
          <h2>Sign In</h2>
          <p>For admin only!</p>
        </div>
      </div>
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
        <div class="modal-body modal-style">
        
          <%= f.label :email %><br />
          <%= f.email_field :email, :autofocus => true %>
  
          <%= f.label :password %><br />
          <%= f.password_field :password %>

          <% if devise_mapping.rememberable? -%>

          <div>
            <%= f.check_box :remember_me %> <%= f.label :remember_me %>
          </div>

          <% end -%>
        </div>

        <div class="modal-footer">
          <%= f.submit "Sign in", :class => 'btn btn-small btn-success' %>
        </div>
      <% end %>    
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse slideDown" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ttt-navigation">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="ttt-navigation">
        
        <ul class="nav navbar-nav">
          <li class="<%= "active" if @active_page == "home" %>" ><%= link_to "Home", root_path %></li>
          <li class="<%= "active" if @active_page == "gallery" %>" ><%= link_to "Gallery", gallery_path %></li>
          <!-- <li class="<%= "active" if @active_page == "blog" %>" ><%= link_to "Blog", blog_path %></li> -->
          <!-- <li class="<%= "active" if @active_page == "contact" %>" ><%= link_to "Contact", contact_path %></li> -->
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Contact <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= mail_to "colby.jarrell@icloud.com" do %>
                  <strong>Email me:</strong> <span>colby.jarrell@icloud.com</span>
                <% end %>
              </li>
              <li>
                <a href="tel:+1-269-420-6106"><strong>Call me:</strong> +1 269 420-6106</a>
              </li>
            </ul>
          </li>
        </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/partials/_post_production_panel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 post-style">
      <p class="body panel-style">This is where info about post production services will go.</p>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-6 gif-frame">
      <%= image_tag "post-production-icon_256_v2.gif", :class => "img-responsive block" %>
    </div>
  </div>
</div>

app/views/partials/_web_development_panel.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-lg-6 post-style">
      <h1 class="tab-header">
        <strong style="color: #F69331">REACTIVE WEBSITES</strong> THAT SHINE,</br>
        EVEN ON YOUR GRANDMAS DEVICE
      </h1>
      <p class="body">This is where information about web development will go.</p>
    </div>
    <div class="col-xs-12 col-md-4 col-lg-6 gif-frame">
      <%= image_tag "web-development-icon_256c_smaller.gif", :class => "img-responsive block" %>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<div class="container">
  <div class="sign-up">
    <%= form_for @post do |f| %>
      <%= f.label :title %><br>
      <%= f.text_field :title %><br>

      <%= f.label :body %><br>
      <%= f.text_area :body %><br>

      <%= f.submit %>
      <% if @post.errors.any? %>
        <div class="post-style">
          <p><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</p>
          <ul class="list">
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <% end %>
  </div>
</div><br>

app/views/posts/edit.html.erb
<h1 class="titles">Edit Post</h1>
<%= render 'posts/form' %>

app/views/posts/new.html.erb
<h1 class="titles">New Post</h1>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<div class="divider">
</div>

<div class="container">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="post-style">
      <h1 class="titles"><%= @post.title %></h1></br>
      <p class="body"><%= @post.body %></p></br>
      <p class="date">Submitted <%= time_ago_in_words(@post.created_at) %> ago.</p>
    </div>
  </div>
</div>